server:
  port: 8081
spring:
  application:
    name: eureka-provider
eureka:
  client:
    service-url:
      #设置服务注册中心地址
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true 
management:
  endpoints:
    web:
      exposure:
        include:
          - shutdown
          - info
          - health
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
